routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/Catalog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Catalog extends Model
{
    use HasFactory;
    protected $table = "catalog";
    public function getImageAttribute()
    {
        return asset('storage/' . $this->photo);
    }
}

app/Http/Controllers/Office/CatalogController.php
<?php

namespace App\Http\Controllers\Office;

use App\Http\Controllers\Controller;
use App\Models\Catalog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Validator;

class CatalogController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keywords = $request->keywords;
            $collection = Catalog::where('titles','like','%'.$keywords.'%')->paginate(10);
            return view('page.office.catalog.list', compact('collection'));
        }
        return view('page.office.catalog.main');
    }
    public function create()
    {
        return view('page.office.catalog.input', ["catalog" => new Catalog]);
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'titles' => 'required|unique:catalog',
            'description' => 'required',
            'price_s' => 'max:19',
            'price_m' => 'max:19',
            'photo' => 'required',
        ]);

        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('titles')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('titles'),
                ]);
            }elseif ($errors->has('description')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('description'),
                ]);
            }elseif ($errors->has('price_s')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('price_s'),
                ]);
            }elseif ($errors->has('price_m')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('price_m'),
                ]);
            }else{
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('photo'),
                ]);
            }
        }
        $file = request()->file('photo')->store("catalog");
        $catalog = new Catalog;
        $catalog->titles = Str::title($request->titles);
        $catalog->description = Str::title($request->description);
        $catalog->price_s = Str::of($request->price_s)->replace(',', '')?:0;
        $catalog->price_m = Str::of($request->price_m)->replace(',', '')?:0;
        $catalog->slug = Str::slug($request->titles);
        $catalog->photo = $file;
        $catalog->save();
        // Client::create($request->all());
        return response()->json([
            'alert' => 'success',
            'message' => 'Catalog '. $request->titles . ' Saved',
        ]);
    }
    public function show(Catalog $catalog)
    {
        //
    }
    public function edit(Catalog $catalog)
    {
        return view('page.office.catalog.input', compact('product'));
    }
    public function update(Request $request, Catalog $catalog)
    {
        $validator = Validator::make($request->all(), [
            'titles' => 'required',
            'description' => 'required',
            'price_s' => 'max:19',
            'price_m' => 'max:19',
        ]);

        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('titles')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('titles'),
                ]);
            }elseif ($errors->has('description')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('description'),
                ]);
            }elseif ($errors->has('price_s')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('price_s'),
                ]);
            }elseif ($errors->has('price_m')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('price_m'),
                ]);
            }
        }
        if(request()->file('photo')){
            Storage::delete($catalog->photo);
            $file = request()->file('photo')->store("catalog");
            $catalog->photo = $file;
        }
        $catalog->titles = Str::title($request->titles);
        $catalog->description = Str::title($request->description);
        $catalog->price_s = Str::of($request->price_s)->replace(',', '')?:0;
        $catalog->price_m = Str::of($request->price_m)->replace(',', '')?:0;
        $catalog->update();
        return response()->json([
            'alert' => 'success',
            'message' => 'Catalog '. $request->titles . ' Updated',
        ]);
    }
    public function destroy(Catalog $catalog)
    {
        Storage::delete($catalog->photo);
        $catalog->delete();
        return response()->json([
            'alert' => 'success',
            'message' => 'Catalog '. $catalog->titles . ' Deleted',
        ]);
    }
}

app/Http/Controllers/User/CatalogController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Catalog;

class CatalogController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keywords = $request->keywords;
            $collection = Catalog::where('titles','like','%'.$keywords.'%')
            ->paginate(10);
            return view('page.web.catalog.list', compact('collection'));
        }
        return view('page.web.catalog.main');
    }
    public function show(Catalog $catalog)
    {
        $collection = Catalog::where('id','!=',$catalog->id)->get();
        return view('page.web.catalog.show',compact('catalog','collection'));
    }
}

app/View/Components/WebLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class WebLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('theme.user.main');
    }
}

resources/views/page/web/catalog/list.blade.php
<div id="shop" class="shop row grid-container leftmargin-sm" data-layout="fitRows">
    @foreach ($collection as $item)
    <div class="product col-lg-3 col-md-4 col-sm-6 col-12">
        <div class="grid-inner">
            <div class="product-image">
                <a href="{{route('user.catalog.show',$item->slug)}}">
                    <img src="{{$item->image}}" alt="{{$item->titles}}">
                </a>
            </div>
            <div class="product-desc">
                <div class="product-title">
                    <h3>
                        <a href="{{route('user.catalog.show',$item->slug)}}">
                            {{$item->titles}}
                        </a>
                    </h3>
                </div>
                <div class="product-price">
                    <ins>
                        Rp. {{number_format($item->price_s)}} - Rp. {{number_format($item->price_m)}}
                    </ins>
                </div>
            </div>
        </div>
    </div>
    @endforeach
</div>

resources/views/page/web/catalog/main.blade.php
<x-web-layout title="Katalog">
    <section id="page-title">
        <div class="container clearfix">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{route('user.home')}}">Home</a></li>
                <li class="breadcrumb-item">
                    <a href="{{route('user.catalog.index')}}">Catalog</a>
                </li>
            </ol>
        </div>
    </section>
    <section id="content">
        <div class="content-wrap">
            <div id="content_list">
                <div id="list_result"></div>
            </div>
        </div>
    </section>
    @section('custom_js')
        <script type="text/javascript">
            load_list(1);
        </script>
    @endsection
</x-web-layout>

resources/views/page/web/catalog/show.blade.php
<x-web-layout title="{{$catalog->titles}}">
    <section id="page-title">
        <div class="container clearfix">
            <h1>{{$catalog->titles}}</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{route('user.home')}}">Home</a></li>
                <li class="breadcrumb-item">
                    <a href="{{route('user.catalog.index')}}">Katalog</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">{{$catalog->titles}}</li>
            </ol>
        </div>
    </section>
    <section id="content">
        <div class="content-wrap">
            <div class="container clearfix">
                <div class="single-product">
                    <div class="product">
                        <div class="row gutter-40">
                            <div class="col-md-5">
                                <!-- Product Single - Gallery ============================================= -->
                                <div class="product-image">
                                    <div class="fslider" data-pagi="false" data-arrows="false" data-thumbs="true">
                                        <div class="flexslider">
                                            <div class="slider-wrap" data-lightbox="gallery">
                                                <div class="slide" data-thumb="{{$catalog->image}}">
                                                    <a href="{{$catalog->image}}" title="{{$catalog->titles}}" data-lightbox="gallery-item">
                                                        <img src="{{$catalog->image}}" alt="{{$catalog->titles}}">
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Product Single - Gallery End -->
                            </div>
                            <div class="col-md-7 product-desc">
                                <!-- Product Single - Short Description ============================================= -->
                                <p>{{$catalog->description}}</p>
                                <!-- Product Single - Short Description End -->
                                <!-- Product Single - Quantity & Cart Button ============================================= -->
                                <form id="form_cart">
                                    <input type="hidden" name="catalog" value="{{$catalog->id}}">
                                    <div class="cart mb-0 d-flex justify-content-between align-items-center">
                                        <div class="product-price">
                                            Harga Siang :
                                            Rp. {{number_format($catalog->price_s)}} <br>
                                            Harga Malam :
                                            Rp. {{number_format($catalog->price_m)}}
                                        </div>
                                        @auth
                                        <button onclick="handle_upload('#tombol_keranjang','#form_cart','{{route('user.order.store')}}','POST','Pesan');" id="tambah_keranjang" class="add-to-cart button m-0">Pesan</button>
                                        @endauth
                                        @guest
                                        <a href="{{route('user.auth.index')}}" class="add-to-cart button m-0">Pesan</a>
                                        @endguest
                                    </div>
                                    <!-- Product Single - Quantity & Cart Button End -->
                                    <div class="line"></div>
                                    <div class="row align-items-center">
                                        <div class="col-sm-6 mb-3">
                                            <h5 class="fw-medium mb-3">Tanggal:</h5>
                                            <input type="text" id="tanggal" name="tanggal" class="form-control" readonly>
                                        </div>
                                        <div class="col-sm-3 mb-3">
                                            <h5 class="fw-medium mb-3">Jam:</h5>
                                            <select class="form-control" id="jam" name="jam"></select>
                                        </div>
                                        <div class="col-sm-3 mb-3">
                                            <h5 class="fw-medium mb-3">Harga:</h5>
                                            <input type="text" id="harga" name="harga" class="form-control" value="0" readonly>
                                        </div>
                                        <div class="col-sm-9 mb-3">
                                            <h5 class="fw-medium mb-3">Jumlah Jam:</h5>
                                            <div class="quantity clearfix">
                                                <input type="button" value="-" class="minus">
                                                <input type="number" maxlength="1" id="total_jam" step="1" min="1" name="total_jam" value="1" title="Total Jam" class="qty" />
                                                <input type="button" value="+" class="plus">
                                            </div>
                                        </div>
                                        <div class="col-sm-3 mb-3">
                                            <h5 class="fw-medium mb-3">Total Harga:</h5>
                                            <input type="text" id="total_harga" name="total_harga" readonly value="0" class="form-control">
                                        </div>
                                        <div class="col-sm-6 mb-3">
                                            <h5 class="fw-medium mb-3">
                                                Harap transfer ke bank BCA<br>
                                                Transfer ke Rekening : xxx-xxx-xxx-xxx<br>
                                                Atas Nama : Nama<br>
                                                Selain no rek diatas, jangan pernah melakukan transfer
                                            </h5>
                                        </div>
                                        <div class="col-sm-6 mb-3">
                                            <h5 class="fw-medium mb-3">Bukti TF:</h5>
                                            <input name="photo" type="file" accept="image/*" class="file-loading image_picker" data-allowed-file-extensions='[]' data-show-preview="false">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    @section('custom_js')
        <script type="text/javascript">
            load_list(1);
            date('tanggal');
            var html = '';
            var sekarang = new Date();
            var day = sekarang.getDate();
            var jam_sekarang = sekarang.getHours();
            var jam_buka = 8;
            var max_jam = 23;
            var tanggal;
            $('#tanggal').datepicker().on('changeDate', function (ev) {
                $("#jam option").remove();
                $("#harga").val(0);
                $("#total_harga").val(0);
                tanggal = $("#tanggal").val();
                $('#jam').append($("<option></option>").attr("value", '').text('Harap pilih jam'));
                if (day == tanggal.substring(0, 2)) {
                    if(jam_sekarang == max_jam){
                        info_toastr('Sudah tutup, harap pilih tanggal lain');
                        $("#tanggal").val('');
                    }else{
                        for (i = jam_sekarang; i < max_jam; i++) {
                            // $(this).append($("<option>").text(i).val(i));
                            $('#jam').append($("<option></option>").attr("value", i).text(i));
                        }
                    }
                }else{
                    for (i = jam_buka; i <= max_jam; i++) {
                        $('#jam').append($("<option></option>").attr("value", i).text(i));
                    }
                }
            });
            $('#jam').on('change', function() {
                if(this.value < 18){
                    $("#harga").val("{{number_format($catalog->price_s)}}");
                }else{
                    $("#harga").val("{{number_format($catalog->price_m)}}");
                }
                var harga = $("#harga").val();
                harga = harga.replace(',','');
                var total_harga = harga * $("#total_jam").val();
                $("#total_harga").val(thousand(total_harga));
            });
            $('#total_jam').on('change', function() {
                var harga = $("#harga").val();
                harga = harga.replace(',','');
                var total_harga = harga * this.value;
                $("#total_harga").val(thousand(total_harga));
            });
        </script>
    @endsection
</x-user-layout>